# -*- coding: utf-8 -*-
"""Copy of TDL_CycleGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPQ-tvhHJfJiw_n60NIi11txE_iwT8RA

## **Build CycleGAN**

### **1. Load Kaggle Datasets for:**
- CAPTCHA Text
- Background Images

### **2. Place CAPTCHA text over background image**
### **3. Save to Colab Directory**
"""

# ✅ Step 1: Install dependencies and create folders
!pip install opendatasets --quiet
!mkdir -p captcha_images styled_captchas

import cv2
import numpy as np
import os
import random
import string
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont
import opendatasets as od

# ✅ Step 2: Download datasets
od.download('https://www.kaggle.com/datasets/fournierp/captcha-version-2-images')
od.download('https://www.kaggle.com/datasets/jessicali9530/stl10')

# ✅ Step 3: Load random STL-10 image from test_images/ directory
def get_random_stl10_image(folder_path):
    img_files = [f for f in os.listdir(folder_path) if f.endswith(('.png', '.jpg'))]
    selected = random.choice(img_files)
    img_path = os.path.join(folder_path, selected)
    img = cv2.imread(img_path)
    return img

# ✅ Step 4: Blend CAPTCHA onto STL-10 background
def overlay_background(captcha_img, background_img):
    captcha_img = cv2.resize(captcha_img, (background_img.shape[1], background_img.shape[0]))
    gray = cv2.cvtColor(captcha_img, cv2.COLOR_BGR2GRAY)
    _, mask = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY_INV)  # Detect text (black)
    mask_inv = cv2.bitwise_not(mask)
    fg = cv2.bitwise_and(captcha_img, captcha_img, mask=mask)
    bg = cv2.bitwise_and(background_img, background_img, mask=mask_inv)
    combined = cv2.add(fg, bg)
    return combined

# ✅ Step 5: Process CAPTCHA images with STL-10 backgrounds
captcha_folder = '/content/captcha-version-2-images/samples/samples'
stl_unlabeled_file = '/content/stl10/test_images'
output_folder = '/content/captcha_images'

for fname in os.listdir(captcha_folder):
    if fname.endswith('.png'):
        captcha = cv2.imread(os.path.join(captcha_folder, fname))
        background = get_random_stl10_image(stl_unlabeled_file)
        background = cv2.resize(background, (captcha.shape[1], captcha.shape[0]))
        result = overlay_background(captcha, background)
        cv2.imwrite(os.path.join(output_folder, f'{fname}'), result)

print("✅ CAPTCHA images with STL-10 backgrounds created.")

"""### **4. Generate Second CAPTCHA dataset**
- Generate random string of length 5 (combination of lowercase English letters & digits)
- Apply the text in contrasting colors for easy human readability
- Apply different fonts for each character separately
- Add the text to a random background image from the dataset
- Add noise and lines to disrupt computer readability

### **5. Save Second CAPTCHA Dataset**
"""

import csv
import os
import random
import string
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

def generate_random_text(length=5):
    allowed_chars = string.ascii_lowercase + string.digits  # only lowercase + digits
    return ''.join(random.choices(allowed_chars, k=length))

def get_contrasting_color(bg_color):
    luminance = (0.299 * bg_color[2] + 0.587 * bg_color[1] + 0.114 * bg_color[0])

    # Slightly adjusted threshold
    if luminance > 160:
        return (40, 40, 40)  # Dark gray instead of pure black
    else:
        return (230, 230, 230)  # Light gray instead of pure white


# === Add noise function ===
def add_noise(image, line_count=5, dot_count=100):
    draw = ImageDraw.Draw(image)

    # Lines
    for _ in range(line_count):
        start = (random.randint(0, image.width), random.randint(0, image.height))
        end = (random.randint(0, image.width), random.randint(0, image.height))
        color = tuple(random.randint(50, 200) for _ in range(3))
        draw.line([start, end], fill=color, width=random.randint(1, 3))

    # Dots
    for _ in range(dot_count):
        x = random.randint(0, image.width - 1)
        y = random.randint(0, image.height - 1)
        color = tuple(random.randint(100, 255) for _ in range(3))
        draw.point((x, y), fill=color)

    return image


# === Modified add_styled_text_per_char function with noise ===
def add_styled_text_per_char(img, text):
    h, w, _ = img.shape
    pil_img = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB)).convert("RGBA")
    bg_color = np.mean(np.mean(np.array(pil_img), axis=0), axis=0).astype(np.uint8)

    fonts = [
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
    ]

    left_margin = int(w * 0.05)
    right_margin = int(w * 0.05)
    usable_width = w - left_margin - right_margin
    char_space = usable_width // len(text)
    max_font_size = int(min(h * 2.2, char_space * 1.9))  # limit by both height and width
    y_center = h // 2

    final_img = pil_img.copy()

    for idx, char in enumerate(text):
        font_size = random.randint(int(max_font_size * 0.8), max_font_size)
        font_path = random.choice(fonts)

        try:
            font = ImageFont.truetype(font_path, font_size)
        except OSError:
            font = ImageFont.load_default()

        char_img = Image.new("RGBA", (char_space, h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(char_img)

        char_color = tuple(random.randint(0, 255) for _ in range(3))
        outline_color = (0, 0, 0)
        stroke_width = 1

        bbox = draw.textbbox((0, 0), char, font=font, stroke_width=stroke_width)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
        x_offset = max((char_space - text_width) // 2, 0)
        y_offset = y_center - text_height // 2 + random.randint(-2, 2)

        draw.text((x_offset, y_offset), char, font=font, fill=char_color + (255,),
                  stroke_width=stroke_width, stroke_fill=outline_color)

        angle = random.randint(-10, 10)
        char_img = char_img.rotate(angle, resample=Image.BICUBIC, expand=True)

        px = left_margin + idx * char_space
        py = 0

        final_img.paste(char_img, (px, py), char_img)

    # ✅ Add noise after all characters are drawn
    final_img_with_noise = add_noise(final_img.convert("RGB"))

    return cv2.cvtColor(np.array(final_img_with_noise), cv2.COLOR_RGB2BGR)


# ✅ Generate and save styled CAPTCHA images
styled_output_folder = '/content/styled_captchas_new'
os.makedirs(styled_output_folder, exist_ok=True)

for i in range(2000):
  bg = get_random_stl10_image(stl_unlabeled_file)
  captcha_text = generate_random_text()
  styled_img = add_styled_text_per_char(bg, captcha_text)
  filename = f"{captcha_text}.png"
  cv2.imwrite(os.path.join(styled_output_folder, filename), styled_img)

print("✅ Styled CAPTCHA images with per-character variation created and saved.")

"""### **6. Combine both CAPTCHA Datasets into Single Dataset**"""

import os
import shutil

# 🔁 Base directory that contains your folders (e.g., styled_captcha_new, captcha_images)
source_dirs = [
    '/content/styled_captchas_new',
    '/content/captcha_images'
]

# 📁 Destination directory where all images will be moved
destination_dir = '/content/all_captchas_combined'
os.makedirs(destination_dir, exist_ok=True)

# 🛠 Move images
for folder in source_dirs:
    for filename in os.listdir(folder):
        if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
            src_path = os.path.join(folder, filename)
            dst_path = os.path.join(destination_dir, filename)

            # Prevent overwriting by renaming duplicates
            base, ext = os.path.splitext(filename)
            counter = 1
            while os.path.exists(dst_path):
                dst_path = os.path.join(destination_dir, f"{base}_{counter}{ext}")
                counter += 1

            shutil.move(src_path, dst_path)  # Use shutil.copy() if you want to keep originals

print(f"✅ All images moved to: {destination_dir}")

"""### **7. Initialize CycleGAN and Install Dependencies**"""

# Commented out IPython magic to ensure Python compatibility.
!rm -rf pytorch-CycleGAN-and-pix2pix
!git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix
# %cd pytorch-CycleGAN-and-pix2pix
!pip install -r requirements.txt

"""### **8. Prepare Train and Test Datasets (A & B)**"""

import os
import shutil
import random
import numpy as np
from PIL import Image, ImageFilter, ImageEnhance
import cv2

# 📂 Setup dataset paths inside the repo (so relative paths work!)
input_folder = "/content/all_captchas_combined"  # <-- your real images
dataset_folder = "./datasets/captcha_gan"        # <-- where CycleGAN looks
trainA = os.path.join(dataset_folder, "trainA")
trainB = os.path.join(dataset_folder, "trainB")
testA = os.path.join(dataset_folder, "testA")
testB = os.path.join(dataset_folder, "testB")

# Create necessary directories
os.makedirs(trainA, exist_ok=True)
os.makedirs(trainB, exist_ok=True)
os.makedirs(testA, exist_ok=True)
os.makedirs(testB, exist_ok=True)

# 🎨 Simple distortion function
def distort_image(img_path):
    img = Image.open(img_path).convert("RGB").resize((256, 256))

    if random.random() > 0.5:
        img = img.filter(ImageFilter.GaussianBlur(radius=random.uniform(0.5, 1.5)))
    if random.random() > 0.5:
        img = ImageEnhance.Contrast(img).enhance(random.uniform(0.7, 1.5))
    if random.random() > 0.5:
        img = ImageEnhance.Brightness(img).enhance(random.uniform(0.7, 1.3))

    # Add random noise
    arr = np.array(img)
    noise = np.random.randint(0, 30, arr.shape, dtype='uint8')
    arr = cv2.add(arr, noise)
    return Image.fromarray(arr)

# 🖼️ Populate trainA (clean) and trainB (distorted)
for file in os.listdir(input_folder):
    if file.endswith(".png"):  # Assuming your images are .png
        src = os.path.join(input_folder, file)
        shutil.copy(src, os.path.join(trainA, file))  # Copy clean image to trainA
        distorted_img = distort_image(src)  # Create distorted version
        distorted_img.save(os.path.join(trainB, file))  # Save to trainB

# 🧑‍💻 Select test samples and copy them to testA and testB
test_size = 50  # Number of test samples to create
samples = random.sample(os.listdir(trainA), test_size)  # Randomly sample files from trainA

for file in samples:
    # Copy from trainA to testA and from trainB to testB
    shutil.copy(os.path.join(trainA, file), os.path.join(testA, file))
    shutil.copy(os.path.join(trainB, file), os.path.join(testB, file))

print("✅ testA and testB created.")

"""### **9. Train CycleGAN to 3 Epochs**"""

!python train.py \
  --dataroot ./datasets/captcha_gan \
  --name captcha_cyclegan \
  --model cycle_gan \
  --gpu_ids 0 \
  --batch_size 4 \
  --no_dropout \
  --n_epochs 3 \
  --n_epochs_decay 0 \
  --display_id -1

"""### **10. Save CAPTCHA Images Generated by CycleGAN**"""

import torch
from torch import nn
from PIL import Image
import os
import numpy as np
import torchvision.transforms as transforms

# ✅ Import the CycleGAN Generator architecture
from models.networks import define_G

# Paths
testA = "/content/pytorch-CycleGAN-and-pix2pix/datasets/captcha_gan/testA"
outputB = "/content/test_results/testB_generated"
os.makedirs(outputB, exist_ok=True)

# Image preprocessing
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
])

# ✅ Define generator architecture
# These params must match how the model was trained
G_A = define_G(input_nc=3, output_nc=3, ngf=64, netG='resnet_9blocks',
               norm='instance', use_dropout=False, init_type='normal', init_gain=0.02, gpu_ids=[])

# ✅ Load the weights into the model
weights_path = '/content/pytorch-CycleGAN-and-pix2pix/checkpoints/captcha_cyclegan/latest_net_G_A.pth'
state_dict = torch.load(weights_path, map_location='cpu')
G_A.load_state_dict(state_dict)
G_A.eval()

# Generate distorted captchas
for filename in os.listdir(testA):
    if filename.endswith(".png"):
        img_path = os.path.join(testA, filename)
        img = Image.open(img_path).convert("RGB")
        img_tensor = transform(img).unsqueeze(0)

        with torch.no_grad():
            fake_B = G_A(img_tensor)[0]

        fake_B = fake_B.cpu().numpy()
        fake_B = np.transpose(fake_B, (1, 2, 0))
        fake_B = ((fake_B + 1) * 127.5).astype(np.uint8)
        Image.fromarray(fake_B).save(os.path.join(outputB, filename))

print("✅ Distorted captchas saved in:", outputB)

from google.colab import drive
drive.mount('/content/drive')

"""### **11. Save Train and Test Datasets in Google Drive**"""

!cp -r /content/test_results/testB_generated /content/drive/MyDrive/captcha_results/v2/

!cp -r /content/all_captchas_combined /content/drive/MyDrive/captcha_backup/

"""## **Test and Improve CAPTCHA**

### **12. CAPTCHA Solver**
"""

from transformers import VisionEncoderDecoderModel, TrOCRProcessor
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import os
from tqdm import tqdm
from torchvision import transforms

# Initialize the processor and model
processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-stage1')
model = VisionEncoderDecoderModel.from_pretrained('microsoft/trocr-base-stage1')

# Set the decoder_start_token_id and pad_token_id manually
model.config.decoder_start_token_id = processor.tokenizer.bos_token_id  # Beginning of sequence token
model.config.pad_token_id = processor.tokenizer.pad_token_id  # Padding token

class CaptchaDataset(Dataset):
    def __init__(self, image_dir, processor, image_size=(384, 384)):
        self.image_dir = image_dir
        self.processor = processor
        self.image_paths = [os.path.join(image_dir, fname) for fname in os.listdir(image_dir) if fname.endswith('.png') or fname.endswith('.jpg')]
        self.image_size = image_size

        # Define a transform to resize images (if necessary)
        self.transform = transforms.Compose([
            transforms.Resize(self.image_size),
            transforms.ToTensor(),
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        image = Image.open(image_path).convert("RGB")
        label = os.path.splitext(os.path.basename(image_path))[0]  # Use filename as label

        # Resize image using the defined transform
        image = self.transform(image)

        # Process image and label
        pixel_values = self.processor(images=image, return_tensors="pt").pixel_values
        labels = self.processor.tokenizer(label, padding="max_length", truncation=True, max_length=32, return_tensors="pt").input_ids

        return pixel_values.squeeze(), labels.squeeze()

def collate_fn(batch):
    pixel_values = torch.stack([item[0] for item in batch])
    labels = torch.stack([item[1] for item in batch])
    return pixel_values, labels

# Directory where your CAPTCHA images are stored
image_dir = '/content/drive/MyDrive/cyclegan_project_backup/datasets/captcha_gan/trainB'

# Create dataset and dataloader
train_dataset = CaptchaDataset(image_dir=image_dir, processor=processor)
train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)

# Setup the device and optimizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch in tqdm(train_dataloader):
        pixel_values, labels = batch
        pixel_values, labels = pixel_values.to(device), labels.to(device)

        # Forward pass
        outputs = model(pixel_values=pixel_values, labels=labels)
        loss = outputs.loss

        # Backward pass
        loss.backward()

        # Update parameters
        optimizer.step()
        optimizer.zero_grad()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

model.save_pretrained('/content/drive/MyDrive/fine_tuned_trocr')

import os
from PIL import Image
from transformers import VisionEncoderDecoderModel, TrOCRProcessor
import torch
import pandas as pd
from tqdm import tqdm

# Load model and processor
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-stage1")
fine_tuned_model = VisionEncoderDecoderModel.from_pretrained("/content/drive/MyDrive/fine_tuned_trocr")
fine_tuned_model.to(device)

# Set required config parameters
fine_tuned_model.config.decoder_start_token_id = processor.tokenizer.bos_token_id
fine_tuned_model.config.pad_token_id = processor.tokenizer.pad_token_id

# Prediction function
def predict_image(image_path):
    image = Image.open(image_path).convert("RGB")
    pixel_values = processor(image, return_tensors="pt").pixel_values.to(device)
    generated_ids = fine_tuned_model.generate(pixel_values)
    generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return generated_text.strip()

# Directory of CAPTCHA images
captcha_dir = "/content/drive/MyDrive/captcha_results"
image_files = [f for f in os.listdir(captcha_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]

# Collect results
results = []
for fname in tqdm(image_files, desc="Running Inference"):
    img_path = os.path.join(captcha_dir, fname)
    actual_text = os.path.splitext(fname)[0]
    predicted_text = predict_image(img_path)
    results.append({
        "Image": fname,
        "Actual": actual_text,
        "Predicted": predicted_text
    })

# Convert to DataFrame
df = pd.DataFrame(results)

# Show results
print(df)

# Optional: Save results to CSV
# df.to_csv("/content/drive/MyDrive/captcha_predictions.csv", index=False)

"""### **13. Adversarial Perturbation Layer**"""

pip install torch torchvision torchattacks --quiet

import torch
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image
import os
from transformers import VisionEncoderDecoderModel, TrOCRProcessor
from tqdm import tqdm

# Set up device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load processor and your fine-tuned model
processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-stage1')
model = VisionEncoderDecoderModel.from_pretrained('/content/drive/MyDrive/fine_tuned_trocr')
model.to(device)
model.eval()

# Image preprocessing transform
transform = transforms.Compose([
    transforms.Resize((384, 384)),
    transforms.ToTensor()
])

# FGSM function
def fgsm_attack(image, epsilon, data_grad):
    sign_data_grad = data_grad.sign()
    perturbed_image = image + epsilon * sign_data_grad
    perturbed_image = torch.clamp(perturbed_image, 0, 1)
    return perturbed_image

# Directory containing original images
image_dir = '/content/drive/MyDrive/captcha_results'
save_dir = '/content/drive/MyDrive/fgsm_captchas'
os.makedirs(save_dir, exist_ok=True)

epsilon = 0.05  # You can tune this

success_count = 0
total = 0

for filename in tqdm(os.listdir(image_dir)):
    if not filename.lower().endswith(('.png', '.jpg', '.jpeg')):
        continue

    # Load and preprocess image
    image_path = os.path.join(image_dir, filename)
    image = Image.open(image_path).convert("RGB")
    image_tensor = transform(image).unsqueeze(0).to(device).requires_grad_()

    # Ground-truth label (from filename)
    label_text = os.path.splitext(filename)[0]
    labels = processor.tokenizer(label_text, padding="max_length", truncation=True, max_length=32, return_tensors="pt").input_ids.to(device)

    # Forward pass
    outputs = model(pixel_values=image_tensor, labels=labels)
    loss = outputs.loss

    # Backward pass
    model.zero_grad()
    loss.backward()

    # Get gradient of the input image
    image_grad = image_tensor.grad.data

    # Generate adversarial image
    perturbed_data = fgsm_attack(image_tensor, epsilon, image_grad)

    # Decode predictions
    with torch.no_grad():
        pred = model.generate(pixel_values=image_tensor)
        adv_pred = model.generate(pixel_values=perturbed_data)

    pred_text = processor.batch_decode(pred, skip_special_tokens=True)[0]
    adv_pred_text = processor.batch_decode(adv_pred, skip_special_tokens=True)[0]

    total += 1
    if pred_text != adv_pred_text:
        success_count += 1

    print(f"\n[{filename}]")
    print(f"Original Prediction : {pred_text}")
    print(f"Adversarial Prediction: {adv_pred_text}")

    # Save adversarial image
    adv_image = perturbed_data.squeeze().detach().cpu()
    adv_pil = transforms.ToPILImage()(adv_image)
    adv_pil.save(os.path.join(save_dir, filename))

# Summary
print(f"\nFGSM Attack Success Rate: {success_count}/{total} ({100*success_count/total:.2f}%)")

"""### **14. Reinforcement Learning for CAPTCHA Difficulty**"""

!pip install stable-baselines3 gymnasium --quiet

!pip install stable-baselines3[extra] tqdm --quiet

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import random

class CaptchaEnv(gym.Env):
    def __init__(self):
        super(CaptchaEnv, self).__init__()

        # Observation = [ai_success_rate, human_success_rate, distortion_level]
        self.observation_space = spaces.Box(low=0.0, high=1.0, shape=(3,), dtype=np.float32)

        # Actions = [0: decrease distortion, 1: keep, 2: increase distortion]
        self.action_space = spaces.Discrete(3)

        # Initial values
        self.distortion_level = 0.0  # Starting distortion (0 to 1)
        self.ai_success_rate = 0.5   # AI starts 50% accurate
        self.human_success_rate = 0.9  # Humans start better
        self.step_count = 0
        self.max_steps = 50

    def reset(self, seed=None, options=None):
        self.distortion_level = 0.0
        self.step_count = 0
        obs = np.array([self.ai_success_rate, self.human_success_rate, self.distortion_level], dtype=np.float32)
        return obs, {}

    def step(self, action):
        # Apply action
        if action == 0:
            self.distortion_level = max(0.0, self.distortion_level - 0.05)
        elif action == 2:
            self.distortion_level = min(1.0, self.distortion_level + 0.1)

        # Simulate AI and Human performance
        ai_prob = max(0.0, 1.0 - (self.distortion_level + np.random.normal(0, 0.05)))
        human_prob = max(0.0, 1.0 - (self.distortion_level * 0.5 + np.random.normal(0, 0.05)))

        # Clip probabilities to [0, 1]
        self.ai_success_rate = np.clip(ai_prob, 0.0, 1.0)
        self.human_success_rate = np.clip(human_prob, 0.0, 1.0)

        # Reward strategy
        reward = 0
        if ai_prob > 0.6:
            reward -= 1  # Penalize if AI easily solves
        elif ai_prob < 0.4 and human_prob > 0.7:
            reward += 1  # Reward if humans solve and AI fails
        elif human_prob < 0.5:
            reward -= 1  # Penalize if humans struggle too much

        self.step_count += 1
        done = self.step_count >= self.max_steps

        obs = np.array([self.ai_success_rate, self.human_success_rate, self.distortion_level], dtype=np.float32)
        return obs, reward, done, False, {}

    def render(self):
        print(f"Distortion: {self.distortion_level:.2f}, AI SR: {self.ai_success_rate:.2f}, Human SR: {self.human_success_rate:.2f}")

from stable_baselines3 import PPO
from stable_baselines3.common.env_checker import check_env

# Now define or reuse CaptchaEnv here (if not already defined above)
env = CaptchaEnv()
check_env(env)

# Train PPO agent
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

# Save the model
model.save("ppo_captcha_difficulty")

env = CaptchaEnv()
model = PPO.load("ppo_captcha_difficulty")

obs, _ = env.reset()
for i in range(50):
    action, _states = model.predict(obs)
    obs, reward, done, _, _ = env.step(action)
    env.render()
    if done:
        break

import os
import random
import numpy as np
import difflib
import re
from PIL import Image
import matplotlib.pyplot as plt
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from stable_baselines3 import PPO
from torchvision import transforms
import torch
import torch.nn.functional as F
import google.generativeai as genai

# Setup Gemini API
genai.configure(api_key="")
gemini_model = genai.GenerativeModel("gemini-1.5-flash")

# Paths
captcha_dir = "/content/drive/MyDrive/fgsm_captchas"
image_files = random.sample(os.listdir(captcha_dir), 10)

# Load TrOCR (AI Solver)
processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-stage1")
model = VisionEncoderDecoderModel.from_pretrained("/content/drive/MyDrive/fine_tuned_trocr-11").to("cpu")

# Load PPO RL agent
env = CaptchaEnv()  # Assuming CaptchaEnv is a predefined environment
ppo_model = PPO.load("ppo_captcha_difficulty", env=env)

# FGSM Distortion function
def apply_fgsm_distortion(img: Image.Image, model, processor, epsilon: float = 0.05) -> Image.Image:
    model.eval()

    # Preprocess image for FGSM
    transform = transforms.Compose([
        transforms.Resize((384, 384)),
        transforms.ToTensor()
    ])
    image_tensor = transform(img).unsqueeze(0).to("cpu").requires_grad_()

    # Ground-truth label from filename is unavailable, so use predicted as pseudo-label
    with torch.no_grad():
        pred_ids = model.generate(pixel_values=image_tensor)
    pseudo_label = processor.batch_decode(pred_ids, skip_special_tokens=True)[0]

    # Tokenize pseudo-label as target
    labels = processor.tokenizer(
        pseudo_label, padding="max_length", truncation=True, max_length=32, return_tensors="pt"
    ).input_ids.to("cpu")

    # Forward pass with label to compute loss
    outputs = model(pixel_values=image_tensor, labels=labels)
    loss = outputs.loss

    # Backward to get gradient
    model.zero_grad()
    loss.backward()
    data_grad = image_tensor.grad.data

    # Apply FGSM
    perturbed_image = image_tensor + epsilon * data_grad.sign()
    perturbed_image = torch.clamp(perturbed_image, 0, 1)

    # Convert to PIL
    adv_image = perturbed_image.squeeze().detach().cpu()
    adv_pil = transforms.ToPILImage()(adv_image)

    return adv_pil

# Text similarity (case-insensitive)
def text_similarity(pred, gt):
    return difflib.SequenceMatcher(None, pred.lower(), gt.lower()).ratio()

# Normalize text for Gemini (remove non-alphanumeric characters)
def normalize_text(text):
    return re.sub(r'\W+', '', text.lower())

# Results tracking
distortions = []

for idx, img_name in enumerate(image_files):
    print(f"\n=== [{idx + 1}/10] ===")
    img_path = os.path.join(captcha_dir, img_name)
    base_img = Image.open(img_path).convert("RGB")

    # Set distortion level from environment
    distortion_level = env.distortion_level

    # AI (TrOCR) prediction
    pixel_values = processor(images=base_img, return_tensors="pt").pixel_values.to("cpu")
    generated_ids = model.generate(pixel_values)
    ai_pred = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()

    # Dummy pass to get logits for confidence calculation
    encoder_outputs = model.get_encoder()(pixel_values)
    decoder_input_ids = torch.tensor([[model.config.decoder_start_token_id]], device="cpu")
    outputs = model(
        encoder_outputs=encoder_outputs,
        decoder_input_ids=decoder_input_ids,
        return_dict=True
    )
    ai_confidence = torch.softmax(outputs.logits, dim=-1).max().item()

    # Decide whether to apply distortion
    if idx == 0:
        distorted_img = base_img
    else:
        # Cap distortion level to avoid over-darkening
        epsilon = min(0.05, distortion_level)
        distorted_img = apply_fgsm_distortion(base_img, model, processor, epsilon=epsilon)

    # Show distorted image
    plt.imshow(distorted_img)
    plt.axis('off')
    plt.title(f"Distortion Level: {distortion_level:.2f}")
    plt.show()

    # Human input
    try:
        human_input = input("Enter CAPTCHA: ").strip()
    except Exception:
        human_input = ""

    # Gemini prediction
    gemini_response = gemini_model.generate_content([
        distorted_img,
        "Extract the CAPTCHA text from this image, without any additional explanation."
    ])
    gemini_pred_raw = gemini_response.text.replace('\n', ' ').strip()
    gemini_pred_clean = normalize_text(gemini_pred_raw)

    # Ground truth
    gt_text = os.path.splitext(img_name)[0]
    gt_clean = normalize_text(gt_text)

    # Similarities
    ai_sim = text_similarity(ai_pred, gt_text)
    gemini_sim_raw = text_similarity(gemini_pred_raw, gt_text)
    gemini_sim_clean = text_similarity(gemini_pred_clean, gt_clean)
    human_sim = text_similarity(human_input, gt_text)

    # Success flags
    ai_success = float(max(ai_sim, gemini_sim_clean) >= 0.6)
    human_success = float(human_sim >= 0.6)

    # Show predictions
    print(f"\n🔐 Actual CAPTCHA    : {gt_text}")
    print(f"🧠 AI Prediction     : {ai_pred} (Sim: {ai_sim:.2f})")
    print(f"🤖 Gemini Prediction : {gemini_pred_raw} (Raw Sim: {gemini_sim_raw:.2f}, Clean Sim: {gemini_sim_clean:.2f})")
    print(f"👤 Human Input       : {human_input} (Sim: {human_sim:.2f})")
    print(f"✅ AI Success: {ai_success}, 👤 Human Success: {human_success}")

    # Final rule: Increase distortion if AI or Gemini succeeded
    override_success = max(ai_sim, gemini_sim_clean) >= 0.6
    if override_success:
        action = 2  # Increase distortion
        print("📈 Increasing distortion (AI or Gemini passed threshold).")
    else:
        # PPO agent decides
        obs = np.array([ai_success, human_success, distortion_level], dtype=np.float32)
        action, _states = ppo_model.predict(obs, deterministic=True)

    # Step the environment
    obs, reward, done, _, _ = env.step(action)
    distortions.append(obs[2])

# Final summary
avg_distortion = sum(distortions) / len(distortions)
print(f"\n📊 Average Recommended Distortion Level: {avg_distortion:.2f}")

import os
import random
import numpy as np
import difflib
import re
from PIL import Image
import matplotlib.pyplot as plt
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from stable_baselines3 import PPO
from torchvision import transforms
import torch
import torch.nn.functional as F
import google.generativeai as genai

# Setup Gemini API
genai.configure(api_key="")
gemini_model = genai.GenerativeModel("gemini-1.5-flash")

# Paths
captcha_dir = "/content/drive/MyDrive/fgsm_captchas"
image_files = random.sample(os.listdir(captcha_dir), 10)

# Load TrOCR (AI Solver)
processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-stage1")
model = VisionEncoderDecoderModel.from_pretrained("/content/drive/MyDrive/fine_tuned_trocr-11").to("cpu")

# Load PPO RL agent
env = CaptchaEnv()  # Assuming CaptchaEnv is defined elsewhere
ppo_model = PPO.load("ppo_captcha_difficulty", env=env)

# FGSM Distortion function
def apply_fgsm_distortion(img: Image.Image, model, processor, epsilon: float = 0.05) -> Image.Image:
    model.eval()
    transform = transforms.Compose([
        transforms.Resize((384, 384)),
        transforms.ToTensor()
    ])
    image_tensor = transform(img).unsqueeze(0).to("cpu").requires_grad_()

    with torch.no_grad():
        pred_ids = model.generate(pixel_values=image_tensor)
    pseudo_label = processor.batch_decode(pred_ids, skip_special_tokens=True)[0]

    labels = processor.tokenizer(
        pseudo_label, padding="max_length", truncation=True, max_length=32, return_tensors="pt"
    ).input_ids.to("cpu")

    outputs = model(pixel_values=image_tensor, labels=labels)
    loss = outputs.loss

    model.zero_grad()
    loss.backward()
    data_grad = image_tensor.grad.data

    perturbed_image = image_tensor + epsilon * data_grad.sign()
    perturbed_image = torch.clamp(perturbed_image, 0, 1)

    adv_image = perturbed_image.squeeze().detach().cpu()
    adv_pil = transforms.ToPILImage()(adv_image)

    return adv_pil

# Text similarity
def text_similarity(pred, gt):
    return difflib.SequenceMatcher(None, pred.lower(), gt.lower()).ratio()

# Normalize for Gemini
def normalize_text(text):
    return re.sub(r'\W+', '', text.lower())

# Store distortion levels
distortions = []

for idx, img_name in enumerate(image_files):
    print(f"\n=== [{idx + 1}/10] ===")
    img_path = os.path.join(captcha_dir, img_name)
    base_img = Image.open(img_path).convert("RGB")

    # Current distortion level from environment
    distortion_level = env.distortion_level

    # AI Prediction
    pixel_values = processor(images=base_img, return_tensors="pt").pixel_values.to("cpu")
    generated_ids = model.generate(pixel_values)
    ai_pred = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()

    # Dummy pass for confidence
    encoder_outputs = model.get_encoder()(pixel_values)
    decoder_input_ids = torch.tensor([[model.config.decoder_start_token_id]], device="cpu")
    outputs = model(
        encoder_outputs=encoder_outputs,
        decoder_input_ids=decoder_input_ids,
        return_dict=True
    )
    ai_confidence = torch.softmax(outputs.logits, dim=-1).max().item()

    # Distortion (if not first)
    if idx == 0:
        distorted_img = base_img
    else:
        epsilon = min(0.1, distortion_level)
        distorted_img = apply_fgsm_distortion(base_img, model, processor, epsilon=epsilon)

    # Show distorted image
    plt.imshow(distorted_img)
    plt.axis('off')
    plt.title(f"Distortion Level: {distortion_level:.2f}")
    plt.show()

    # Human input
    try:
        human_input = input("Enter CAPTCHA: ").strip()
    except Exception:
        human_input = ""

    # Gemini prediction
    gemini_response = gemini_model.generate_content([
        distorted_img,
        "Extract the CAPTCHA text from this image, without any additional explanation."
    ])
    gemini_pred_raw = gemini_response.text.replace('\n', ' ').strip()
    gemini_pred_clean = normalize_text(gemini_pred_raw)

    # Ground Truth
    gt_text = os.path.splitext(img_name)[0]
    gt_clean = normalize_text(gt_text)

    # Similarity Scores
    ai_sim = text_similarity(ai_pred, gt_text)
    gemini_sim_raw = text_similarity(gemini_pred_raw, gt_text)
    gemini_sim_clean = text_similarity(gemini_pred_clean, gt_clean)
    human_sim = text_similarity(human_input, gt_text)

    # Success Flags
    ai_success = float(max(ai_sim, gemini_sim_clean) >= 0.6)
    human_success = float(human_sim >= 0.6)

    # Show predictions
    print(f"\n🔐 Actual CAPTCHA    : {gt_text}")
    print(f"🧠 AI Prediction     : {ai_pred} (Sim: {ai_sim:.2f})")
    print(f"🤖 Gemini Prediction : {gemini_pred_raw} (Raw Sim: {gemini_sim_raw:.2f}, Clean Sim: {gemini_sim_clean:.2f})")
    print(f"👤 Human Input       : {human_input} (Sim: {human_sim:.2f})")
    print(f"✅ AI Success: {ai_success}, 👤 Human Success: {human_success}")

    # Custom rule-based adjustment of distortion
    if ai_success >= 0.6:
        if human_success < 0.5:
            # AI succeeds, human fails -> decrease distortion
            env.distortion_level = max(0.01, env.distortion_level - 0.05)
        elif human_success >= 0.6:
            # Both succeed -> increase distortion
            env.distortion_level = min(0.9, env.distortion_level + 0.1)
        else:
            # AI only succeeds, human unclear -> small increase
            env.distortion_level = min(0.9, env.distortion_level + 0.05)
    elif ai_success < 0.6:
        if human_success < 0.6:
            # Both fail -> decrease distortion
            env.distortion_level = max(0.01, env.distortion_level - 0.05)
        else:
            # Human only succeeds -> keep distortion level the same
            pass

    distortions.append(env.distortion_level)


# Summary
avg_distortion = sum(distortions) / len(distortions)
print(f"\n📊 Average Recommended Distortion Level: {avg_distortion:.2f}")